version: 2
project_name: lisa

before:
  hooks:
    - go test ./...

builds:
  - id: lisa
    main: .
    binary: lisa
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }} -X main.date={{ .Date }}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    files:
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: lisa
    repository:
      owner: bma-d
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/bma-d/lisa
    description: tmux orchestrator for Claude/Codex AI agent sessions.
    install: |
      bin.install "lisa"
    test: |
      system "#{bin}/lisa", "version"

nfpms:
  - id: lisa
    package_name: lisa
    homepage: https://github.com/bma-d/lisa
    description: tmux orchestrator for Claude/Codex AI agent sessions.
    maintainer: bma-d
    formats:
      - deb
      - rpm
      - apk
